# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

env:
  - TOXENV=py27

#  - TOXENV=py26
#  - TOXENV=py33

#==================================== ERRORS ====================================
#
#__________ ERROR collecting tests/app/OriExport_to_shapefile_test.py ___________
#
#ImportError while importing test module '/home/travis/build/yoyonel/2016_ENSG_PYTHON_COURS/tests/app/OriExport_to_shapefile_test.py'.
#
#Original error message:
#
#'cannot import name 'euler_matrix''
#
#Make sure your test modules/packages have valid Python names.
#
#!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
#  - TOXENV=py34

install: pip install tox

script: tox

notifications:
email: false
